# The dataset - Iris

In [1]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()

iris_dataset.keys()

print("DESCRIPTION")
print(iris_dataset['DESCR'][:193] + "\n ...")

print("target_names")
print("---")
print(iris_dataset['target_names'])
print("")

print("feature_names")
print("---")
print(iris_dataset [ 'feature_names' ])
print("")

print('{}'.format(type ( iris_dataset [ 'data' ])))


DESCRIPTION
Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
 ...
target_names
---
['setosa' 'versicolor' 'virginica']

feature_names
---
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

<type 'numpy.ndarray'>


In [2]:
print("SHAPE")
print("---")
print(iris_dataset['data'].shape)
print()

SHAPE
---
(150, 4)
()


In [3]:
iris_dataset [ 'data' ][: 5 ]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

# Training and Testing

In [4]:
from sklearn.model_selection import train_test_split
import datetime

I considered using epoch as random seed but can only take 2\*\*32-1 as largest number.
Docs say "random_state=0" but looks like it might be better to just _not_ set it and use defaul value "None" which uses "np.random".

reference: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html instead did not set 

other stuff:

shuffle : boolean, optional (default=True)

In [26]:
X_train,X_test,y_train,y_test = train_test_split(iris_dataset['data'],iris_dataset['target'])

In [27]:
X_train[:5]

array([[6.4, 3.2, 5.3, 2.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.6, 1.4, 0.2]])

In [12]:
X_test[1:5]

array([[6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2]])

In [13]:
y_train

array([1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2,
       1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1,
       0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2,
       2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1,
       2, 0])

In [14]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [15]:
print ( "X_train shape: %s " % str ( X_train . shape ))
print ( "y_train shape: %s " % str ( y_train . shape ))

X_train shape: (112, 4) 
y_train shape: (112,) 


In [16]:
print ( "X_test shape: %s " % str ( X_test . shape ))
print ( "y_test shape: %s " % str ( y_test . shape ))

X_test shape: (38, 4) 
y_test shape: (38,) 


Examine the data, make a matrix of 2d comparisons

In [29]:
import pandas as pd

# create dataframe from data in X_train
# label the columns using the strings in iris_dataset.feature_names

iris_dataframe = pd.DataFrame( X_train, columns=iris_dataset.feature_names )

# create a scatter matrix from the dataframe, color by y_train

grr = pd.scatter_matrix( iris_dataframe, c=y_train, figsize=(15,15 ), marker='o' , hist_kwds={ 'bins':20}, s=60 , alpha=.8 , cmap =mglearn.cm3 )

ImportError: No module named pandas